name: Build

on: 
  push:
    branches:
      - unstable
  pull_request:
    branches:
      - unstable

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Ant build
        run: ant -noinput -buildfile build.xml clean check jar unittest
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: openrocket_build_${{ github.run_number }}
          path: ${{github.workspace}}/swing/build/jar/OpenRocket.jar

